---

- name: "Instlacja git 2.x"
  hosts: "{{ var_host | default('blueocean') }}"
  tasks:
    - name: "Deinstalacja git 1.x"
      yum:
        name:
          - git
        state: absent
    - name: "Sciagniecie pakietu endpoint"
      get_url:
        url: https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
        dest: /tmp/endpoint-repo.x86_64.rpm
    - name: "Instalacja pakietu endpoint" 
      yum:
        name: /tmp/endpoint-repo.x86_64.rpm
        state: present
    - name: "Instlacja git2.x"
      yum:
        name:
          - git.x86_64
        state: present
