---
- name: "Instlacja ssh"
  hosts: "{{ var_host | default('blueocean') }}"
  tasks:
    - name: "Instalacja komponentow ssh" 
      yum:
        name: 
          - openssh.x86_64
          - openssh-server.x86_64
          - openssh-clients.x86_64
          - openssh-askpass.x86_64
        state: present
        update_cache: yes
