---
- name: "Instlacja srodowiska R"
  hosts: "{{ var_host | default('blueocean') }}"
  tasks:
    - name: "Instalacja zalenosci dla srodowiska R" 
      yum:
        name: 
          - bzip2.x86_64
          - bzip2-devel.x86_64
          - xz.x86_64
          - xz-devel.x86_64
          - pcre.x86_64
          - pcre-devel.x86_64
          - pcre2.x86_64
          - pcre2-devel.x86_64
          - cairo.x86_64
          - cairo-devel.x86_64
          - libcurl.x86_64
          - libcurl-devel.x86_64
          - libjpeg-turbo.x86_64
          - libjpeg-turbo-devel.x86_64
          - libtiff.x86_64
          - libtiff-devel.x86_64
          - libpng.x86_64
          - libpng-devel.x86_64
          - readline.x86_64
          - readline-devel.x86_64
          - libX11-devel.x86_64
          - libXt-devel.x86_64
          - xorg-x11-server-devel.x86_64
          - tcl.x86_64
          - tcl-devel.x86_64
          - tk.x86_64
          - tk-devel.x86_64
          - java.x86_64
          - java-devel.x86_64
          - which.x86_64
        state: present
        update_cache: yes
