---

- name: "Instlacja srodowska soge submit noda"
  hosts: "{{ var_host | default('blueocean') }}"
  tasks:
    - name: "Instalacja zaleznosci soge do poprawnego dzialania submit node"
      yum:
        name:
          - jemalloc
        state: present
        update_cache: yes
