---
- name: "Instalacja srodowiska nvidia-docker"
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
  - name: Install apt-transport-https
    apt: name=apt-transport-https state=present

  - name: Add Docker repository key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker repository source
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      state: present
      update_cache: no

  - name: Add NVidia-Docker repository key
    apt_key:
      url: https://nvidia.github.io/nvidia-docker/gpgkey
      state: present

  - name: Add NVidia-Docker repository source
    get_url:
      url: https://nvidia.github.io/nvidia-docker/{{ ansible_distribution | lower }}{{ ansible_distribution_version }}/nvidia-docker.list
      dest: /etc/apt/sources.list.d/nvidia-docker.list
      owner: root
      group: root
      mode: 0644

  - name: Install nvidia-docker2
    apt: name=nvidia-docker2 state=latest update_cache=yes
    register: nvidia_docker_apt

  - name: Reload Docker configuration
    service: name=docker state=reloaded
    when: nvidia_docker_apt.changed == True

  - name: Montowanie RSP
    raw: mfsmount -H mfsmaster.dev.p.lodz.pl -S /blueocean/opt /srv/blueocean/opt

  - name: Kopiowanie pliku konfiguracyjnego dockera
    copy:
     src: /srv/blueocean/opt/software/Blueocean/Configs/docker_hosts/daemon.json
     dest: /etc/docker/daemon.json

  - name: Odmontowanie RSP
    raw: umount /srv/blueocean/opt

  - name: Przeladowanie konfiguracji dockera
    command: pkill -SIGHUP dockerd 
