---

- name: "Instlacja narzedzi uzytkownika noda boaccess"
  hosts: "{{ var_host | default('blueocean') }}"
  tasks:
    - name: "Instalacja filebead 7.13.3"
    - raw: yum -y install https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.13.3-x86_64.rpm 
