---
- name: "LVM - lokalna konfiguracja"
  hosts: "{{ var_host | default('blueocean') }}"
  tasks:
    - name: "Rozszerzenie volumentu lvroot:"
      lvol:
        vg: vgroot
        lv: lvroot
        size: 6144
    - name: "Rozszerzenie systemu plikow xfs:"
      filesystem:
        fstype: xfs
        dev: /dev/vgroot/lvroot
        resizefs: yes
